### ISSUE TITLE
Max pooling in attention module

### ISSUE THREAD

**Issue by ligua** [voletiv/self-attention-GAN-pytorch#1]
Hi, Great work!!!

May I ask why there is a maxpool2d function in the attention module? 

Thanks!!

**Comment by voletiv** [comment]
Hi, thank you!
I'm not exactly sure, because I didn't create it myself, I simply copies the exact architecture as in the Google Brain repo. But I would guess it is for the same reason pooling was invented - to bottleneck the right features.
