### ISSUE TITLE
injecting noise in images fed to disc

### ISSUE THREAD

**Issue by mostel** [voletiv/self-attention-GAN-pytorch#3]
I haven't checked the Google Brain code thoroughly, but I don't think they inject noise on the generated or real images before feeding them to the discriminator. Are you sure they do this?

**Comment by voletiv** [comment]
No, they don't do this in their repo, you're right. But I have found that this helps in some cases, so I just wanted to add the option.

I just run it with `--inst_noise_sigma 0`, that doesn't inject any noise.
