### ISSUE TITLE
About the hyperparameter and model architecture

### ISSUE THREAD

**Issue by yueruchen** [voletiv/self-attention-GAN-pytorch#5]
Hi, thanks for your work. Is this repo contains the exactly same hyperparameters and model architecture with that of https://github.com/brain-research/self-attention-gan?
Thanks!

**Comment by voletiv** [comment]
Yes, I initialized with the defaults from the brain-research repository. But there are inherent differences in TF and PyTorch that don't allow the hyperparameters to transfer seamlessly.
